### ISSUE TITLE
Friends API - Getting Friends returns empty list

### ISSUE THREAD

**Issue by Octopusghost** [Sanjay-B/Pyblox#9]
Code:
```
from pyblox3 import Friends

def GetAllFriends():
    FriendsPage1 = Friends.friendList(1)
    print(FriendsPage1)

GetAllFriends()
```

Issue: When you run this command it comes up with the output https://gyazo.com/6d12f5f5b8a0afda3488df8f5318d0fa since it's not taking the friend list from a user.

**Comment by sbhadr** [comment]
Hey, 
I can't seem to produce this error. Are you sure that you have friends on that account? If you don't, it will return an empty table.

**Comment by sbhadr** [comment]
After reviewing this, I noticed that you set the parameter of ``Friends.friendList(1)`` wrong. ``1`` is supposed to be the user_id of your user. Closing.
